### PR TITLE
Run on Node16 using actions/checkout@v3

### PR DESCRIPTION
**Pull request by m-linner-ericsson**
### Applicable Issues

None

### Description of the Change

As per https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ GitHub will stop supporting Node 12. actions/checkout@v3 uses Node 16 as per https://github.com/actions/checkout/releases/tag/v3.0.0

### Alternate Designs

I could not think of any other design

### Benefits

Enables us to continue running GitHub Actions

### Possible Drawbacks

None that I have seen

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Mattias Linnér, mattias.linner@ericsson.com

### CODE REVIEW

**Comment by magnusbaeck** [comment]
How about setting up Dependabot to do stuff like this for us?

**Comment by m-linner-ericsson** [comment]
> How about setting up Dependabot to do stuff like this for us?

Hmm, I thought Dependabot was for security updates https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide but maybe you can do it for other things also

**Comment by magnusbaeck** [comment]
Oh, sure. We have configured e.g. eiffel-goer to get action updates from Dependabot.

**Comment by m-linner-ericsson** [comment]
> Oh, sure. We have configured e.g. eiffel-goer to get action updates from Dependabot.

Thanks for the tip, fixed in [68ee0d0](https://github.com/eiffel-community/eiffel/pull/367/commits/68ee0d0abf1865ffc3c815a0555c5de8aaace641)

**Review by t-persson — APPROVED** [review]

**Review by magnusbaeck — APPROVED** [review]

**Pull request merged**
